In [1]:
import matplotlib.pyplot as plt
from cvxopt import matrix, solvers
import numpy as np
import random
from SoccerWorld import player, game

In [44]:

num_actions = 5
num_rows = 2
num_cols = 4
num_states = num_rows * num_cols * 2 #2
qtable = np.zeros(shape=(num_states, num_actions, num_actions), dtype='float')


In [45]:
c = matrix([0., 0., 0., 0., 0., -1.])

In [71]:
G = qtable[2, :, :]
G = np.hstack((G, np.ones((num_actions, 1)) * -1.))
G = -G
G

array([[-0., -0., -0., -0., -0.,  1.],
       [-0., -0., -0., -0., -0.,  1.],
       [-0., -0., -0., -0., -0.,  1.],
       [-0., -0., -0., -0., -0.,  1.],
       [-0., -0., -0., -0., -0.,  1.]])

In [72]:
q = np.ones(num_actions+1) * 1.
q[-1] = 0
G = np.vstack((G, q))
q = np.ones(num_actions+1) * -1.
q[-1] = 0
G = np.vstack((G, q))
G

array([[-0., -0., -0., -0., -0.,  1.],
       [-0., -0., -0., -0., -0.,  1.],
       [-0., -0., -0., -0., -0.,  1.],
       [-0., -0., -0., -0., -0.,  1.],
       [-0., -0., -0., -0., -0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  0.],
       [-1., -1., -1., -1., -1.,  0.]])

In [73]:
q = np.hstack((np.eye(num_actions)*-1., np.zeros((num_actions,1))))
G = np.vstack((G,q))
print (G)
G = matrix(G)
G

[[-0. -0. -0. -0. -0.  1.]
 [-0. -0. -0. -0. -0.  1.]
 [-0. -0. -0. -0. -0.  1.]
 [-0. -0. -0. -0. -0.  1.]
 [-0. -0. -0. -0. -0.  1.]
 [ 1.  1.  1.  1.  1.  0.]
 [-1. -1. -1. -1. -1.  0.]
 [-1. -0. -0. -0. -0.  0.]
 [-0. -1. -0. -0. -0.  0.]
 [-0. -0. -1. -0. -0.  0.]
 [-0. -0. -0. -1. -0.  0.]
 [-0. -0. -0. -0. -1.  0.]]


<12x6 matrix, tc='d'>

In [74]:
c = np.zeros((num_actions+1))
c[-1] = -1
print (c)
c = matrix(c)
print (c)


[ 0.  0.  0.  0.  0. -1.]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[-1.00e+00]



In [75]:
b = np.zeros((num_actions))
b = np.hstack((b, [1,-1]))
b = np.hstack((b, np.zeros(num_actions)))
print (b)
b = matrix(b)
print (b)

[ 0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 1.00e+00]
[-1.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]



In [88]:
sol = solvers.lp(c,G,b, solver='glpk')
print (type(np.array(sol['x'][:5]).reshape(1,5)[0]))
print (type(sol['x'][5]))

<class 'numpy.ndarray'>
<class 'float'>
