In [4]:
import numpy as np
import math
import matplotlib.pyplot as plt
%matplotlib inline
np.set_printoptions(suppress=True)

In [5]:
# first let's create the start state 
state = np.zeros((7))
state[3] = 1
state

seq = state
seq

loc = np.argwhere(state)
loc = loc[0][0]
loc

sequence_array = []

In [6]:
all_array = []

for j in range(100):
    sequence_array = []
    for i in range(10):
        state = np.zeros((7), dtype=np.int)
        state[3] = 1
        seq = state
        loc = np.argwhere(state)[0][0]

        while loc != 0 and loc != state.shape[0] - 1:
            if np.random.rand() <= 0.5:
                loc += -1
            else:
                loc += 1
            state = np.zeros(7)
            state[loc] = 1
            seq = np.vstack((seq, state))
        sequence_array.append(seq)
    all_array.append(sequence_array)
print all_array[0][9]
    


[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]


In [7]:
def rmse(predictions, targets):
    return np.sqrt(np.mean((predictions-targets)**2))

In [29]:
Z = np.array([0., 1./6, 1./3, 1./2, 2./3, 5./6, 1])


# for i in range(10):
#     sequence = ten_sequence[i]
alpha = 0.5
lam = 0.5

rm_all = np.zeros(len(all_array))


w_0 = np.array([0, 1./2, 1./2, 1./2, 1./2, 1./2, 1])
e_s = np.zeros(7)



sequence = np.array([[0., 0., 0., 1., 0., 0., 0.],
                     [0., 0., 0., 0., 1., 0., 0.],
                     [0., 0., 0., 0., 0., 1., 0.],
                     [0., 0., 0., 0., 1., 0., 0.],
                     [0., 0., 0., 0., 0., 1., 0.],
                     [0., 0., 0., 0., 1., 0., 0.],
                     [0., 0., 0., 0., 0., 1., 0.],
                     [0., 0., 0., 0., 0., 0., 1.]])
val_update = np.zeros(7)
for t in range(len(sequence)-1):

    delta = (w_0[sequence[t+1] == 1] - w_0[sequence[t] == 1])[0]
    e_s[sequence[t] == 1] = e_s[sequence[t] == 1] + 1
    for w in range(len(w_0)):
        val_update[w] = val_update[w] + alpha * delta * e_s[w]
        e_s[w] = lam * e_s[w]
print val_update[1:-1]
w_0 = w_0 + val_update



[0.         0.         0.00390625 0.1640625  0.328125  ]


In [36]:
Z = np.array([0., 1./6, 1./3, 1./2, 2./3, 5./6, 1])


# for i in range(10):
#     sequence = ten_sequence[i]
alpha = 1
lam = 0.5

rm_all = np.zeros(len(all_array))


w_0 = np.array([0, 1./2, 1./2, 1./2, 1./2, 1./2, 1])
e_s = np.zeros(7)



sequence = all_array[0][0]
val_update = np.zeros(7)
for t in range(len(sequence)-1):

    delta = (w_0[sequence[t+1] == 1] - w_0[sequence[t] == 1])[0]
    e_s[sequence[t] == 1] = e_s[sequence[t] == 1] + 1
    for w in range(len(w_0)):
        val_update[w] = val_update[w] + alpha * delta * e_s[w]
        e_s[w] = lam * e_s[w]
print val_update[1:-1]
w_0 = w_0 + val_update



[0.      0.      0.03125 0.3125  0.625  ]


In [ ]:
e_s = np.zeros(7)
sequence = all_array[0][0]
val_update = np.zeros(7)
for t in range(len(sequence)-1):

    delta = (w_0[sequence[t+1] == 1] - w_0[sequence[t] == 1])[0]
    e_s[sequence[t] == 1] = e_s[sequence[t] == 1] + 1
    for w in range(len(w_0)):
        val_update[w] = val_update[w] + alpha * delta * e_s[w]
        e_s[w] = lam * e_s[w]
print val_update[1:-1]