In [3]:
from cvxopt import matrix, solvers
import numpy as np

In [73]:
A = [[0.0, 2.63, -4.9], [-2.63, 0.0, 1.0], [4.9, -1.0, 0.0]]

In [74]:
num_vars = len(A)
c = [-1] + [0 for i in range(num_vars)]
c = np.array(c, dtype="float")
c = matrix(c)

In [75]:
# constraints G*x <= h
G = np.matrix(A, dtype='float').T
G *= -1
G = np.vstack([G, np.eye(num_vars) * -1]) # >0 constraint for all
new_col = [1 for i in range(num_vars)] + [0 for i in range(num_vars)]
new_col
G = np.insert(G, 0, new_col, axis=1) #insert utility column
G = matrix(G)

In [76]:
h = ([0 for i in range(num_vars)] + [0 for i in range(num_vars)])
h = np.array(h, dtype='float')
h = matrix(h)

In [77]:
# constraints Ax = b
A = [0] + [1 for i in range(num_vars)]
A = np.matrix(A, dtype='float')
A = matrix(A)
print (A)

b = np.matrix(1, dtype='float')
b = matrix(b)

[ 0.00e+00  1.00e+00  1.00e+00  1.00e+00]



In [78]:
sol = solvers.lp(c=c, G=G, h=h, A=A, b=b, solver ='glpk')

In [88]:
print (sol['x'][1])

0.11723329425556858


In [61]:
print (G)

[ 1.00e+00  0.00e+00  1.00e+00 -1.00e+00]
[ 1.00e+00 -1.00e+00  0.00e+00  1.00e+00]
[ 1.00e+00  1.00e+00 -1.00e+00  0.00e+00]
[ 0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00]
[ 0.00e+00 -0.00e+00 -1.00e+00 -0.00e+00]
[ 0.00e+00 -0.00e+00 -0.00e+00 -1.00e+00]



In [62]:
print (h)

[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]



In [63]:
print (A)

[ 0.00e+00  1.00e+00  1.00e+00  1.00e+00]



In [64]:
print (b)

[ 1.00e+00]



In [65]:
print(c)


[-1.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]

