In [74]:
import mdptoolbox
import numpy as np
from math import ceil, log
import json

In [94]:
number_of_states = 30
probs = np.zeros((2, number_of_states, number_of_states))

# to go right with action 0
for i in range(0, number_of_states-1):
    probs[0, i, i+1] = 1
    
# to go left with action 1
for i in range(1, number_of_states):
    probs[1, i, i-1] = 1

    
# this are terminal states
probs[0, -1, -1] = 1
probs[1, -1, -2] = 1 
probs[1, 0, 0] = 1

probs[1, 15:, 15:]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [95]:
probs[1,29,:]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])

In [96]:
# rewards is action and state and also next state based 

rewards = np.zeros((2, number_of_states, number_of_states))

rewards[0,:,:] = -1
rewards[1,:,:] = 1
rewards[0,-2,-1] = 999999


rewards

gamma = 0.75

In [97]:
pi = mdptoolbox.mdp.PolicyIteration(probs, rewards, gamma, eval_type=1)
pi.run()

In [98]:
pi.iter

29

In [83]:
pyDict = {'gamma':0.75}

In [84]:
states = []
for i in range(number_of_states):
    dicted = {}
    dicted['id'] = i
    
    
    actions = []
    for act in range(2):
        act_dict = {}
        
        tr_dict = {}
        tr_dict['id'] = 0
        to = np.where(probs[act, i, :])[0][0]
        tr_dict['probability'] = probs[act, i, to] 
        tr_dict['reward'] = rewards[act, i, to]
        tr_dict['to'] = to
        tr_list = []
        tr_list.append(tr_dict)
        act_dict['transitions'] = tr_list 
        act_dict['id'] = act
        actions.append(act_dict)
        
    
    dicted['actions'] = actions
    
    states.append(dicted)
states

pyDict['states'] = states

In [85]:
probs[1,0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
dict_to_json = json.dumps(pyDict, indent=4)

In [87]:
pyDict

{'gamma': 0.75,
 'states': [{'actions': [{'id': 0,
     'transitions': [{'id': 0, 'probability': 1.0, 'reward': -1.0, 'to': 1}]},
    {'id': 1,
     'transitions': [{'id': 0, 'probability': 1.0, 'reward': 1.0, 'to': 0}]}],
   'id': 0},
  {'actions': [{'id': 0,
     'transitions': [{'id': 0, 'probability': 1.0, 'reward': -1.0, 'to': 2}]},
    {'id': 1,
     'transitions': [{'id': 0, 'probability': 1.0, 'reward': 1.0, 'to': 0}]}],
   'id': 1},
  {'actions': [{'id': 0,
     'transitions': [{'id': 0, 'probability': 1.0, 'reward': -1.0, 'to': 3}]},
    {'id': 1,
     'transitions': [{'id': 0, 'probability': 1.0, 'reward': 1.0, 'to': 1}]}],
   'id': 2},
  {'actions': [{'id': 0,
     'transitions': [{'id': 0, 'probability': 1.0, 'reward': -1.0, 'to': 4}]},
    {'id': 1,
     'transitions': [{'id': 0, 'probability': 1.0, 'reward': 1.0, 'to': 2}]}],
   'id': 3},
  {'actions': [{'id': 0,
     'transitions': [{'id': 0, 'probability': 1.0, 'reward': -1.0, 'to': 5}]},
    {'id': 1,
     'transition

In [88]:
with open('data.json', 'w') as outfile:
    json.dump(pyDict, outfile, indent=2)

In [63]:
probs[0,0,0]

1.0