In [169]:
import matplotlib.pyplot as plt
from cvxopt import matrix, solvers
import numpy as np
import random
from SoccerWorld import player, game

In [215]:
a = np.array([[6., 2],
              [7,0]])
b = np.array([[6., 2],
              [7,0]])

In [216]:
arr = np.zeros((a.shape[0]**2))
z = np.zeros((a.shape[0]**2))
for i in range(a.shape[0]):
    for j in range(a.shape[0]):
        if i != j:
            q = a[j] - a[i]
            n = i * (a.shape[0])
            arr[n:n+a.shape[0]] = q 
            z = np.vstack((z, arr))
            arr = np.zeros((a.shape[0]**2))
# print (z)
            
for i in range(b.shape[0]):
    for j in range(b.shape[0]):
        if i != j:
            l = np.transpose(np.array(range(a.shape[0]**2)).reshape(a.shape[0],a.shape[0])).reshape(a.shape[0]**2)  
            
            q = b[j] - b[i]
            n = i * (a.shape[0])
            for kk in range(q.shape[0]):
                arr[l[kk]+i] = q[kk]
                
            z = np.vstack((z, arr))
            arr = np.zeros((a.shape[0]**2))
G = np.delete(z, 0, axis=0)
print(z)

[[ 0.  0.  0.  0.]
 [ 1. -2.  0.  0.]
 [ 0.  0. -1.  2.]
 [ 1.  0. -2.  0.]
 [ 0. -1.  0.  2.]]


In [217]:
eye = np.eye(G.shape[1]) * -1
G = np.vstack((G, eye))

In [218]:
G

array([[ 1., -2.,  0.,  0.],
       [ 0.,  0., -1.,  2.],
       [ 1.,  0., -2.,  0.],
       [ 0., -1.,  0.,  2.],
       [-1., -0., -0., -0.],
       [-0., -1., -0., -0.],
       [-0., -0., -1., -0.],
       [-0., -0., -0., -1.]])

In [219]:
q = np.ones(a.shape[0]**2) * 1.
G = np.vstack((G, q))
q = np.ones(a.shape[0]**2) * -1.
G = np.vstack((G, q))

In [220]:
G

array([[ 1., -2.,  0.,  0.],
       [ 0.,  0., -1.,  2.],
       [ 1.,  0., -2.,  0.],
       [ 0., -1.,  0.,  2.],
       [-1., -0., -0., -0.],
       [-0., -1., -0., -0.],
       [-0., -0., -1., -0.],
       [-0., -0., -0., -1.],
       [ 1.,  1.,  1.,  1.],
       [-1., -1., -1., -1.]])

In [221]:
b = np.zeros((G.shape[0], 1))
b[-2] = 1
b[-1] = -1

In [222]:
c = np.zeros((a.shape[0] ** 2))
c = matrix(c)
print (c)

[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]



In [223]:
G = matrix(G)
b = matrix(b)

In [224]:
sol = solvers.lp(c,G,b, solver='glpk')

In [226]:
np.array(sol['x']).reshape(a.shape[0], a.shape[0])

array([[0.5 , 0.25],
       [0.25, 0.  ]])